# Generated by Django 4.1.3 on 2022-12-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
    ]
